### ISSUE TITLE
Possible error with validation of non-required fields

### ISSUE THREAD

**Issue by 0xAX** [jonasschmidt/ex_json_schema#13]
Hello @jonasschmidt,

I'm using `ex_json_schema` for validation of an API by the given [swagger](http://swagger.io/) specification and I'm getting error that:

`{:invalid, {"Required property Feild2 was not present.", "#"}}`

My schema looks:

```
"post": {
  "parameters": [
   {
     "name": "FooObject",
     "in": "body",
     "required": true,
     "schema": {
       "$ref": "#/definitions/Foo"
    }
   }],
```

The `Foo` is object with fields where some of them are required and others not:

```
"Foo": {
  "type": "object",
  "required": [
    "Field1"
  ],
  "properties": {
    "Field1": {
      "$ref": "#/definitions/Field1"
    },
    "Field2": {
      "$ref": "#/definitions/Field2"
    }
}
```

How can I fix this?

Thank you

**Comment by jonasschmidt** [comment]
Hey. Can you provide a bit more context about what exactly you're trying to do? Which part of that Swagger schema are you using as the JSON Schema, and what is the JSON payload you're validating?

**Comment by 0xAX** [comment]
Hi, 

> Which part of that Swagger schema are you using as the JSON Schema

I'm using [phoenix_swagger](https://github.com/xerions/phoenix_swagger) to parse swagger schema into json schema. Actually it just takes two parts of any swagger schema: `paths` and `definitions`.

> Which part of that Swagger schema are you using as the JSON Schema, and what is the JSON payload you're validating?

For example:

```
{"Field1", "foo bar"}
```

for the schema which I've posted above:

```
"Foo": {
  "type": "object",
  "required": [
    "Field1"
  ],
  "properties": {
    "Field1": {
      "$ref": "#/definitions/Field1"
    },
    "Field2": {
      "$ref": "#/definitions/Field2"
    }
}
```

Is it clear or you need more details?

Thank you.

**Comment by jonasschmidt** [comment]
Ok, so I had a look at what phoenix_swagger is doing with the Swagger schema to turn it into a JSON Schema to validate parameters against. There's a bunch of code that tries to determine which parameters are required and merges everything into one JSON Schema that is then used to validate all the params against (https://github.com/xerions/phoenix_swagger/blob/master/lib/phoenix_swagger/validator.ex#L116-L138). I'm not exactly sure what the end result of those transformations is, and there is also no test for that case in the phoenix_swagger test suite (in fact there is no test for body parameters at all, which are handled differently from path/query/header params in Swagger).

So as long as I don't know what the actual JSON Schema is that it then uses to validate some params map, I can't really figure out what could be the problem. It's very unlikely that there's a bug around required parameters in ex_json_schema since all that logic is validated several times, both against the official JSON Schema test suite and additional unit tests.

In general, the approach taken in phoenix_swagger falls a bit short and covers only a fraction of what the Swagger schema has to say about validation. And I suspect that some parts of it are also not exactly conforming to the specification. I think it mostly works for checking if some query parameters are there or not.

That being said, I am currently working on an actual Swagger validator in Elixir (https://github.com/jonasschmidt/ex_swagger) that will fully conform to the Swagger specification when it's done. There are some parts of the Swagger schema that use a subset of JSON Schema, but there's also a big part of it that's custom and can't be easily mapped to JSON Schema. There are still some things that need to be implemented, but the parts that are there are thoroughly tested. It will probably take me a few more weeks to have the remaining parts implemented and have things in a state where I can push out an initial version.

**Comment by 0xAX** [comment]
Hello @jonasschmidt, thank you for such detailed reply.

> In general, the approach taken in phoenix_swagger falls a bit short, and covers only a fraction of what the Swagger schema has to say about validation.

Yes, maybe. I will check it there. Only one question: I see that `required` fields are represented as list. For example `["foo", "bar", "baz"]`. 

What if I have following definition in my schema:

```
"definitions": {
   "MyObject": {
    "type": "object",
    "required": ["Foo", "Bar"],
    "properties": {
       "Foo": {
         "type": "string"
       },
       "Bar": {
         "type": "object",
         "$ref": "#/definitions/Baz"
       }
     }
   }
   "Baz": {
     "required": ["Foo1", "Bar1"]
     ...
     ...
     ...
   }
}
```

How to collect required fields in this way? Should it be `["Foo", "Bar", "Foo1", "Bar1"]` or something else? Actually I'm confusing how to be with `Foo1` and `Bar1` fields in this case

Thank you.

**Comment by 0xAX** [comment]
Yes, seems it is error of phoenix_swagger. So Im closing the issue. @jonasschmidt  thank you for the help
