### ISSUE TITLE
Tuple support?

### ISSUE THREAD

**Issue by vadim-moz** [jonasschmidt/ex_json_schema#2]
Currently, `array` (in JSON) has 1-to-1 correspondence to `list`. It is probably right decision for pure JSON validator, although dependent on JSON parser. 

I'm considering to use the validator to verify general data structure. In order to do that, I would need to specify that certain piece is tuple. OTOH, proper representation for JSON `array` in some cases is tuple too. 

What would be your opinion about making tuple support conditional, based on configuration? For example, `config ..., tuple_type: true` to allow to specify tuple type as similar to `array`, but mapped to tuple, and `config ..., array_maps_to: <:list | :tuple | :list_or_tuple >`? 

I could try to prepare PR if you are interested.

Thank you.

**Comment by jonasschmidt** [comment]
It sounds like a bit of a specialized use case to me, but if it's only about tuples as arrays (and not something like using proplists/tuples for the whole data structure), then it should be straight-forward enough to add, without breaking existing functionality.

I don't even think it needs a configuration option, since we can just pattern match on the type of the data in https://github.com/jonasschmidt/ex_json_schema/blob/master/lib/ex_json_schema/validator/items.ex and do a `Tuple.to_list` when `items` is a tuple.

Would a solution like that fit your needs?

I can give it a go in a few days, or you can submit a PR and I will have a look.

**Comment by vadim-moz** [comment]
Thank you for your generous offer. Let me try to prepare a PR.

**Comment by jonasschmidt** [comment]
Hey. Is this still and issue for you? And are you still planning on submitting a PR? Otherwise I would close it for now and re-open if it comes up again.

**Comment by vadim-moz** [comment]
Thank you for reminder. Let me re-evaluate our plans.

Can I add that this is an excellent package? Thank you very much!

**Comment by jonasschmidt** [comment]
Alright, no hurry. Just wanted to make sure this isn't already resolved. And thank you very much :)
