### ISSUE TITLE
Validator throws exception on unexpected input

### ISSUE THREAD

**Issue by technomage** [jonasschmidt/ex_json_schema#20]
If an object is provided to be validated that has unexpected type (atom in this case), the validator throws an exception inType.data_type. There should be an else on the cold returning something that indicates an unexpected type.

**Comment by jonasschmidt** [comment]
My reasoning to not deal with this case was that JSON Schema has no concept of an atom as a data type, and and atom can't really be something that comes as an input from the outside world and is part of a data structure to be validated. So there must already be some logic in your program that "makes" those atoms. And if that's the case, why do you have to validate it afterwards?

Maybe I'm missing something here, since it's a question that came up several times. Maybe if you explain the use case a bit, I can understand why this is something that should be dealt with by the validator.

**Comment by technomage** [comment]
The atoms came from the use of the validator to validate method call data from a business logic component, that receives input from both a web component, and other sources.  Having an atom as a value is an error as you suggest, but since it can happen when provided maps from an elixir client, it would be better if the validator reported an error rather than an exception.  I can do a pull request with the changes.  It is just better coding style, and quite applicable when used to validate maps that can come from more than a JSON parser.

**Comment by leifg** [comment]
Ran in the same issue.

My reasoning was that atoms will just be converted in strings anyway, so no need to explicitly convert them.

Regardless of the validity in providing `atoms` in a response the error that is thrown is `** (CondClauseError) no cond clause evaluated to a true value`. This is a cryptic and required me to debug the library. Something like this could be very useful:

```
defp data_type(data) do
  cond do
    is_nil(data) -> "null"
    is_boolean(data) -> "boolean"
    is_binary(data) -> "string"
    is_integer(data) -> "integer"
    is_number(data) -> "number"
    is_list(data) -> "array"
    is_map(data) -> "object"
    true ->
     IO.warn("Unknown type for #{inspect(data)}")
     false
  end
end
```

**Comment by jonasschmidt** [comment]
Better handling of unknown types was added in version `0.6.1`: https://github.com/jonasschmidt/ex_json_schema/blob/master/lib/ex_json_schema/validator/type.ex#L46
