### ISSUE TITLE
Error messages could be better for oneOf, anyOf, allOf

### ISSUE THREAD

**Issue by technomage** [jonasschmidt/ex_json_schema#22]
It would be helpful if the error messages for these combining properties included the failure messages for their component schemas when they fail.  Thus for oneOf show the messages from all failing items if any when it fails to match, or list the number of passing matches if more than one.  anyOf should show failures if none match, and all of should show all failures.

**Comment by jonasschmidt** [comment]
Yes, you're absolutely right. I did not do this for the sake of simplicity, and also because it is really challenging to interpret these kinds of errors. Especially when you're dealing with multiple levels of `oneOf`s and `anyOf`s.

I have an open branch that is addressing several open issues regarding error formats (https://github.com/jonasschmidt/ex_json_schema/tree/validation-errors). I will see if it would be easier to include this change in the scope of those changes. Unfortunately, I can't say when this will be ready for a release yet. I've had very little time to work on this project in the past months.

**Comment by ananthakumaran** [comment]
I understand there is work going on in a separate branch but is it possible to merge a short-term solution to this issue? maybe https://github.com/jonasschmidt/ex_json_schema/pull/23. In my case, there is an `anyOf`  in the topmost level, which makes the error messages nearly useless

**Comment by ananthakumaran** [comment]
Sure, no need to make a release, I can directly test the branch. Are the changes on `validation-errors` branch?

**Comment by ananthakumaran** [comment]
Thanks, so far from my testing, the errors returned are lot more informative. As it's an internal api, I am using `inspect` for formatting now, which is kind of OK for now. Have you thought about how to format `anyOf` etc?, I am not sure how it would map to a flat list of `{error, path}` tuple

**Comment by jonasschmidt** [comment]
The final version is released as `0.6.0` now, there are some examples in the README of how to use the error formatting.
