### ISSUE TITLE
Unknown validators by typo are always valid

### ISSUE THREAD

**Issue by tokubass** [jonasschmidt/ex_json_schema#26]
The following test succeed due to typo.

```
 assert valid?(%{"typee" =>  "integer" }, "a") == true
```

What is the correct way to prevent typo ?
- add function to `ex_json_schema` ?  
- make wrapper module ?

**Comment by jonasschmidt** [comment]
JSON Schema ignores additional/unknown properties in the schema (like `typee` in your example) in order to be easily extensible. You can have a look at the draft 4 meta-schema here: http://json-schema.org/draft-04/schema (it's surprisingly simple).

I don't think that's something that can be solved on a library level, because people could use their schema to add all sorts of additional properties. You could define your own meta-schema (based on the draft 4 meta-schema) and use that custom meta-schema to validate your schema.

**Comment by tokubass** [comment]
thank you.
I wil try locking properties on a application level.
