### ISSUE TITLE
Invalid response validates successfully.

### ISSUE THREAD

**Issue by afulki** [jonasschmidt/ex_json_schema#30]
I came accross the following issue while testing a response from a server we are developing, 

## The JSON Object definition
```json
{
  "$schema": "http://json-schema.org/schema#", 
  "type": "object", 
  "properties": {
    "getSampleResponse": {
      "required": [
        "samples"
      ], 
      "type": "object", 
      "properties": {
        "samples": {
          "items": {
            "type": "object", 
            "properties": {
              "dateField": {
                "type": "string", 
                "format": "date"
              }, 
              "stringField": {
                "type": "string"
              }
            }
          }, 
          "type": "array"
        }
      }
    }
  }
}
```

## The reponse tested agaisnt the JSON Object definition

```json
{
    "getSampleResponse": {
        "samples": [],
        "samples": {
            "dateField": "2018-03-19",
            "stringField": "USD"
        }
    }
}
```
Notice how the output has both a samples array (empty) and a sample object (which really should be an instance of the items json nested within the array), validating the above is succesful.

## Validation code

```elixir
      case ExJsonSchema.Validator.validate(schema, data) do
        :ok -> {:ok, options, []}
        {:error, list} -> pretty_print(list)
      end
```

**Comment by jonasschmidt** [comment]
The problem here is that your JSON isn't valid JSON. You can try it on https://jsonlint.com/ or any other linter and it will tell you that it's invalid. Different JSON parsers will do all sorts of things in that case, many of them don't treat it as an error, but just silently pick one or the other value. For example, Poison will pick the first value for `sample` (`[]`), and Ruby's standard JSON library will pick the second (`{"dateField": "2018-03-19", "stringField": "USD"}`).

Since there's no defined behaviour for that case, there's nothing we can do about it here. `ex_json_schema` does not deal with JSON strings, it will work on Elixir data structures (= `Map`), and an Elixir/Erlang `Map` can't have duplicate keys.

**Comment by afulki** [comment]
Thanks for the response,

Yes I spotted the format of the JSON was invalid, was hoping for a single function to validate, i.e. this does not match the JSON Object definition (quite apart from being invalid JSON) and that I would see an error.  I will look for a lint-library to check the message first. 

Thanks again, the library has proved very useful!

Gary
